CREATE TABLE [dbo].[Beams]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Standard] NVARCHAR(50) NOT NULL,
    [Modified] BIT NOT NULL DEFAULT 0,
    [Metric] BIT NOT NULL DEFAULT 1,
    [Preferred] BIT NOT NULL DEFAULT 0,
    [Variation] NVARCHAR(50) NOT NULL, 
    [Designation] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(50) NOT NULL,
    [G] FLOAT NULL,
    [h] FLOAT NOT NULL,
    [b] FLOAT NOT NULL,
    [s] FLOAT NULL,
    [t] FLOAT NULL,
    [A] FLOAT NULL,
    [r1] FLOAT NULL,
    [r2] FLOAT NULL,
    [Beta] FLOAT NULL,
    [Ix] FLOAT NULL,
    [Sx] FLOAT NULL,
    [Rx] FLOAT NULL,
    [Iy] FLOAT NULL,
    [Sy] FLOAT NULL,
    [Ry] FLOAT NULL,
    [Tr] FLOAT NULL,
    [Ts] FLOAT NULL,
    [Verified] BIT NOT NULL DEFAULT 0,
    [Reference] NVARCHAR(50) NULL,
    [Official] BIT NOT NULL DEFAULT 1,
    [Comments] NVARCHAR(500) NULL,
    [Date] DATETIME NULL,
    [Active] BIT NULL DEFAULT 1,
    [Uploader] NVARCHAR(50) NULL,
    [Access] NVARCHAR(200) NULL
);